version: 0.2
phases:
  install:
  runtime-versions:
    nodejs: 16
  commands:
    - npm install --legacy-peer-deps
  build:
    commands:
      - echo "Building project..."
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: dist

